variables:
  NAME: 'what-happen'
  VERSION: 'v1.0.0'
  IMAGE_NAME: ${NAME}:${VERSION}
stages:
  - master

master:
  stage: master
  only:
    - master
  tags:
    - online
  script:
    - rm -rf node_modules
    - yarn
    - cp .env.example .env
    - yarn build
    - cd docker
    - docker build --no-cache -t ${IMAGE_NAME} .
    - docker-compose up -d
