import {
    WeiBo, Baidu, DouYin, ThePaper, TouTiao, _36kr, Blbl, CankaoXiaoxi,
    ItHome, Jin10, nowcoder, PcBeta, Solidot,
    TieBa, V2ex, WallStreetCN, Hotstock, Zaobao, Kaopu, Kuaishou, Zhihu,
    Coolapk, Hupu, Juejin, Douban, LoL, KuGou, QQMusic, CSDN, Sspai, Jqka, _51Cto, Dongchedi, Fishpi, AutoHome
} from "@/components/icon";
import {Coffee, DollarSign, Radio, Github} from 'lucide-vue-next'
// 平台图标映射
export const PlatformIcons = {
    weibo: WeiBo,
    baidu: Baidu,
    douyin: DouYin,
    thepaper: ThePaper,
    github: Github,
    toutiao: TouTiao,
    '_36kr': _36kr,
    b_hot_search: Blbl,
    b_hot_video: Blbl,
    b_rank: Blbl,
    cankaoxiaoxi: CankaoXiaoxi,
    gelonghui: DollarSign,
    guoheboke: Coffee,
    ithome: ItHome,
    jin10: Jin10,
    nowcoder: nowcoder,
    pcbeta_windows: PcBeta,
    solidot: Solidot,
    sputniknewscn: Radio,
    tieba: TieBa,
    v2ex: V2ex,
    wallstreetcn_live: WallStreetCN,
    wallstreetcn_news: WallStreetCN,
    wallstreetcn_hot: WallStreetCN,
    hotstock: Hotstock,
    zaobao: Zaobao,
    cls_telegraph: DollarSign,
    kaopu: Kaopu,
    kuaishou: Kuaishou,
    zhihu: Zhihu,
    coolapk: Coolapk,
    hupu: Hupu,
    juejin: Juejin,
    douban: Douban,
    bd_tv: Baidu,
    hupu_lol: LoL,
    kugou: KuGou,
    qq_music: QQMusic,
    csdn: CSDN,
    sspai: Sspai,
    jqka: Jqka,
    _51cto: _51Cto,
    dcd_hot: Dongchedi,
    dcd_news: Dongchedi,
    fishpi: Fishpi,
    autohome: AutoHome,
    autohome_hot: AutoHome,
    autohome_article: AutoHome,
    autohome_video: AutoHome,
}
